services:
  order_service:
    build:
      context: ..
      dockerfile: sync-rest/order_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      INVENTORY_URL: http://inventory_service:8001
      NOTIFICATION_URL: http://notification_service:8002
      DB_PATH: /data/shared.db
    volumes:
      - ../common/db/shared.db:/data/shared.db
    depends_on:
      - inventory_service
      - notification_service

  inventory_service:
    build:
      context: ..
      dockerfile: sync-rest/inventory_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      DB_PATH: /data/shared.db
    volumes:
      - ../common/db/shared.db:/data/shared.db

  notification_service:
    build:
      context: ..
      dockerfile: sync-rest/notification_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      DB_PATH: /data/shared.db
    volumes:
      - ../common/db/shared.db:/data/shared.db
